### ISSUE TITLE
DCAT format needs a tweak

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/getdata#6]
I think the output of the distributions is not quite right. 
If a publisher has more than one dataset, it should sit as an array in the distributions section.

I think the current behaviour is to make a new entry completely.
This needs to be fixed in Salesforce

**Comment by timgdavies** [comment]
Ah - I think this might make the script to generate output in Salesforce a bit more complex - but certainly do-able. 

Let me know if this is something you need me to look at - although I think you have already been doing work on updating those scripts?

**Comment by caprenter** [comment]
Thanks @timgdavies. I'll have a go in a Sandbox and see where I get to, then pull you in if needed.

**Comment by caprenter** [comment]
I had a look at this today but didn't get anywhere

**Comment by timgdavies** [comment]
ok - let's catch up next week. My hunch is that it will need something a bit hacky like:
- Sorting the output of the SOQL query by publisher;
- Storing the current publisher in a lastPublisher variable;
- Checking each time around the loop if current publisher = lastPublisher and only outputting the publisher part of distribution then;

**Comment by Bjwebb** [comment]
> If a publisher has more than one dataset, it should sit as an array in the distributions section.

I don't think this is quite right.

As I understand it, our JSON feed is a list of **datasets**, each of which can have multiple **distributions**. In the case of 360Giving, an example of the difference would be:
- Publisher: The Wolfson Foundation
- Dataset: The Wolfson Foundation Grants 2014
- Distribution: The Wolfson Foundation Grants 2014 Excel
- A different distribution for the same dataset could be: The Wolfson Foundation Grants 2014 CSV

At the moment I think we only have one distribution for each dataset (because we removed the CSV in cases where we had both CSV and Excel), so I think that the current JSON is correct.

However, I think there is extra work to do if we want to supply multiple formats of the same data correctly.

**Comment by BibianaC** [comment]
@timgdavies @Bjwebb Can this issue be closed?

**Comment by Bjwebb** [comment]
I think so.
